# 本文件为本地测试配置
# 配置方法：复制本文件并重命名为 `default.yml`，修改 `default.yml` 中的内容
app:
  addr: ":3456"
  prefix: "/api"
mongodb:
  host: "127.0.0.1"
  username: "carrot"
  password: "123"
  database: "carrot"
qqbot:
  name: "middleware" # 修改为你的 QQ bot 账号名(匹配 @ 时使用)
  host: "http://127.0.0.1:5701"
  qq: 1000000000 # 修改为你的 QQ bot 账号

plugin:
  default:
    admin: 1000000000 # 修改为你的 QQ 账号
  weather:
    host: "https://api.seniverse.com/v3/weather/daily.json"
    token: "SRw2t5tNFjmvTEkF2"
  homework:
    admin: 1000000000 # 修改为你的 QQ 账号
    group: 1000000000 # 修改为你的测试群聊
  food:
    admin: 1000000000 # 修改为你的 QQ 账号
    group: 1000000000 # 修改为你的测试群聊
  schedule:
    admin: 1000000000 # 修改为你的 QQ 账号
    group: 1000000000 # 修改为你的测试群聊
  codeforces:
    admin: 1000000000 # 修改为你的 QQ 账号
    group: 1000000000 # 修改为你的测试群聊

risk-control: false # 当前风控，群聊功能关闭
database-use: true # 测试环境没有运行 mongo 数据库