# 本文件为部署配置
app:
  addr: ":3456"
  prefix: "/api"
mongodb:
  host: "127.0.0.1"
  username: "carrot"
  password: "123"
  database: "carrot"
qqbot:
  name: "卡洛塔"
  host: "http://127.0.0.1:5700"
  qq: 2919327775

plugin:
  default:
    admin: 2039799616
  weather:
    host: "https://api.seniverse.com/v3/weather/daily.json"
    token: "SRw2t5tNFjmvTEkF2"
  homework:
    admin: 2039799616
    group: 923300200
  food:
    admin: 2039799616
    group: 923300200

risk-control: false # 当前风控，群聊功能关闭
database-use: true # 测试环境是否运行 mongo 数据库