app:
  addr: ":3456"
  prefix: "/api"
mongodb:
  host: "127.0.0.1"
  username: "carrot"
  password: "123"
  database: "carrot"
qqbot:
  host: "http://127.0.0.1:5701"
  qq: 100000000 # 你的 QQ bot 账号

plugin:
  default:
    admin: 100000000 # 你的 QQ 账号
  weather:
    host: "https://api.seniverse.com/v3/weather/daily.json"
    token: "SRw2t5tNFjmvTEkF2"
  homework:
    admin: 100000000
    group: 100000000
  food:
    admin: 100000000
    group: 100000000

risk-control: true # 当前风控，群聊功能关闭
database-use: false # 测试环境没有运行 mongo 数据库